name: Build and Deploy
# Trigger ON
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install

    - name: Lint the code
      run: yarn run lint

    - name: Build the application
      run: yarn run build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: List dist directory contents (optional)
        run: ls -la dist  # Optional step to verify build contents

      - name: Copy files to the root of the subdomain
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "Copying files to /youturn.10torsions.com..."
          ftp -inv $FTP_SERVER <<EOF
            user $FTP_USERNAME $FTP_PASSWORD
            lcd dist
            cd /youturn.10torsions.com
            mput *
            bye
          EOF

      - name: List files on the server after upload (optional)
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "Listing files on the server after upload..."
          ftp -inv $FTP_SERVER <<EOF
            user $FTP_USERNAME $FTP_PASSWORD
            cd /youturn.10torsions.com/
            ls
            bye
          EOF